version: '3.9'

services:
  go-bulletin:
    container_name: go-bulletin
    image: francescoxx/go-app:1.0.0
    build: .
    environment:
      DATABASE_URL: "host=go_postgres user=postgres password=postgres dbname=postgres sslmode=disable"
    ports:
      - "8000:8000"
    depends_on:
      - go_postgres
  go_postgres:
    container_name: go-postgres
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgres/data

volumes:
  pgdata: {} 